### ISSUE TITLE
Add projects link in navbar 

### ISSUE THREAD

**Issue by gauthamzz** [opencode18/OpenCode-Collaborative#194] opened 2018-01-11 21:09 UTC

**Comment by Jigar3** [comment] 2018-01-11 21:28
I would like to take this issue

**Comment by gauthamzz** [comment] 2018-01-11 21:31
@Jigar3 cool

**Comment by pradeepgangwar** [comment] 2018-01-12 04:45
@gauthamzz duplicate issue. #167

**Comment by pradeepgangwar** [comment] 2018-01-12 08:00
Closing this as duplicate of #167

**Closed by pradeepgangwar** 2018-01-12 08:00 UTC
Labels: Rookie: 10 Points, assigned
