### ISSUE TITLE
Remove the underline on hovering over the forks and stars icons .

### ISSUE THREAD

**Issue by pranjalg2308** [opencode18/OpenCode-Collaborative#296] opened 2018-01-14 12:53 UTC
![fork](https://user-images.githubusercontent.com/35169520/34916108-5e5a36c6-f958-11e7-9912-0536923c7ca8.png)

**Comment by pranjalg2308** [comment] 2018-01-14 12:56
i would like to do it

**Comment by muskan6769** [comment] 2018-01-14 14:00
can I do it

**Comment by pradeepgangwar** [comment] 2018-01-14 14:19
duplicate of #288

**Closed** 2018-01-14 16:07 UTC
Labels: duplicate, invalid
