### ISSUE TITLE
Add Issues of all projects in the Issue section.

### ISSUE THREAD

**Issue by aswanthkoleri** [opencode18/OpenCode-Collaborative#256] opened 2018-01-13 09:08 UTC
As of now, only the OpenCode collabarative and Codestash repo's issues are being shown in the issue section.Add the issues of all the projects registered under OpenCode. You can refer the Main Website for getting the list of all the projects that Opencode is serving.

**Comment by Ace-Bansal** [comment] 2018-01-13 09:16
I'd like to work on this

**Comment by pradeepgangwar** [comment] 2018-01-13 09:31
@Ace-Bansal  assigned

**Comment by pradeepgangwar** [comment] 2018-01-13 09:32
@aswanthkoleri But this is duplicate of #250

**Closed** 2018-01-13 09:45 UTC
Labels: Opencode18, duplicate, not-available
